apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: result
  labels: 
    app: vote-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: result
      app: vote-app
  template: 
    metadata:
      name: result
      labels:
        name: result
        app: vote-app
    spec: 
      containers: 
      - name: result
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
          name: result