apiVersion: v1 
kind: Service 
metadata: 
  name: db
  labels:
    name: db 
    app: vote-app
spec:
  type: ClusterIP 
  ports:
  - port:  5432
    targetPort: 5432
    name: "postgres-service"
  selector: 
    name: db
    app: vote-app